### PR TITLE
[AUT-6164][AUT-6854] add configs to acp-cd chart

### PR DESCRIPTION
**Pull request by ppodbielski-cloudentity**
## Description
- add the possibility to add config.yaml and extraconfig.yaml
- add the possibility to configure rootCa

## Information for QA

- [x] Is QA testing required?
- [ ] Does PR contain unit tests?
- [ ] Should QA create E2E tests for the change?

example:
```
## ACP http client configuration
##
client:
  rootCa: |
    -----BEGIN CERTIFICATE-----
    certyficatecertyficatecertyficate
    -----END CERTIFICATE-----

## Enable Default ACP config
##
config:
  ## The data should match acp configuration options
  ## https://docs.operations.cloudentity.com/reference/acp-configuration/
  ##
  data:
    client:
        insecure_skip_verify: false
```
```
---
# Source: acp-cd/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: RELEASE-NAME-acp-cd
  labels:
    helm.sh/chart: acp-cd-2.2.1
    app.kubernetes.io/name: acp-cd
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "2.2.1"
    app.kubernetes.io/managed-by: Helm
stringData:
  clientID: YnZnN2h2YzA1NnV0YmdpaHF1OWcK
  clientSecret: aE0wdmYwZHNBMHkxSHBHZW1WXzlDa21iYmlOclp2NW92S1JDTm5hd2pJbwo
  issuerURL: https://acp.acp-system:8443/default/system
---
# Source: acp-cd/templates/tls-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: RELEASE-NAME-acp-cd-client-tls
  labels:
    helm.sh/chart: acp-cd-2.2.1
    app.kubernetes.io/name: acp-cd
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "2.2.1"
    app.kubernetes.io/managed-by: Helm
data:
  client-ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCmNlcnR5ZmljYXRlY2VydHlmaWNhdGVjZXJ0eWZpY2F0ZQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
---
# Source: acp-cd/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: RELEASE-NAME-acp-cd
  labels:
    helm.sh/chart: acp-cd-2.2.1
    app.kubernetes.io/name: acp-cd
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "2.2.1"
    app.kubernetes.io/managed-by: Helm
data:
  seed.yaml: |
    apis: []
    audit_events: []
    cdr_arrangements: []
    ciba_authentication_services: []
    claims: []
    clients: []
    consent_actions: []
    consent_grants: []
    consents: []
    cross_tenant_api_policy_bindings: []
    gateway_api_groups: []
    gateways: []
    idps: []
    mfa_methods: []
    openbanking_br_consents: []
    openbanking_file_payment_consent_file_resources: []
    openbanking_uk_consents: []
    policies: []
    policy_execution_points: []
    privacy_ledger_events: []
    quota_usage: []
    recurring_jobs: []
    scope_grants: []
    scopes_without_service: []
    script_execution_points: []
    scripts: []
    secrets: []
    server_consents: []
    servers: []
    servers_bindings: []
    services: []
    tenant: {}
    vanity_domains: []
  config.yaml: |
    client:
      root_ca: /tls/client-ca.crt
  extraconfig.yaml: |
    client:
      insecure_skip_verify: false
---
# Source: acp-cd/templates/import.yaml
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    helm.sh/chart: acp-cd-2.2.1
    app.kubernetes.io/name: acp-cd
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "2.2.1"
    app.kubernetes.io/managed-by: Helm
  name: RELEASE-NAME-acp-cd
  annotations:
    helm.sh/hook: post-install,post-upgrade
spec:
  backoffLimit: 4
  template:
    spec:
      imagePullSecrets:
        - name: docker.cloudentity.io
      volumes:
        - name: import
          configMap:
            name: RELEASE-NAME-acp-cd
        - name: tls
          projected:
            defaultMode: 384
            sources:
            - secret:
                name: RELEASE-NAME-acp-cd-client-tls
      containers:
        - name: acp-cd
          image: "docker.cloudentity.io/acp:2.2.1"
          imagePullPolicy: IfNotPresent
          args:
            - import
            - --client-id
            - "$(CLIENT_ID)"
            - --client-secret
            - "$(CLIENT_SECRET)"
            - --issuer-url
            - "$(ISSUER_URL)"
            - --mode
            - update
            - --format
            - yaml
            - --input
            - /import/seed.yaml
            - --config
            - /data/config.yaml,/data/extraconfig.yaml
            
          env:
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: RELEASE-NAME-acp-cd
                  key: clientID
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: RELEASE-NAME-acp-cd
                  key: clientSecret
            - name: ISSUER_URL
              valueFrom:
                secretKeyRef:
                  name: RELEASE-NAME-acp-cd
                  key: issuerURL
          volumeMounts:
            - mountPath: /import
              name: import
              readOnly: true
            - mountPath: /tls
              name: tls
              readOnly: true
            
      restartPolicy: Never
```

### CODE REVIEW

**Comment by holowinski** [comment]
How is the customConfig flag supposed to be used?
Shouldn't it be added to the values file for reference?

**Review by lgonczarik — APPROVED** [review]

**Comment by ppodbielski-cloudentity** [comment]
> How is the customConfig flag supposed to be used? Shouldn't it be added to the values file for reference?

https://github.com/cloudentity/acp-helm-charts/pull/197/files#diff-46568ca90c242120c1da068bc2ae9b5c74456b43965b29f5a7c84f827fc43faaR53
you can define own configmap with e.g my-own-config.yaml

```
## Enables custom config
##
customConfig: my-own-config.yaml
```
then will have:
```
      containers:
        - name: acp-cd
          image: "docker.cloudentity.io/acp:2.2.1"
          imagePullPolicy: IfNotPresent
          args:
            - import
 (...)
            - --input
            - /import/seed.yaml
            - --config
            - my-own-config.yaml
```

**Review by artursmolarek — APPROVED** [review]
Please remember to update Operations docs.

**Review by ppodbielski-cloudentity — COMMENTED** [review]
needs to be merged with:
https://github.com/cloudentity/acp-saas/pull/794

**Review by lradosz — APPROVED** [review]

**Comment by lradosz** [comment]
it doesn't work

```{"error":"could not create http transport: failed to read http client root ca: open /tls/client-ca.crt: permission denied","level":"fatal","msg":"failed to get http client","time":"2022-05-28T01:02:03Z"}```

values file: 

```
##
client:
  rootCa: |
    -----BEGIN CERTIFICATE-----
    MIIDjjCCAnYCCQCkYimCrjt5tDANBgkqhkiG9w0BAQsFADCBiDELMAkGA1UEBhMC
    VVMxCzAJBgNVBAgMAldBMRAwDgYDVQQHDAdTZWF0dGxlMRQwEgYDVQQKDAtDbG91
    ZGVudGl0eTELMAkGA1UECwwCU0UxEzARBgNVBAMMCmFjcC1zeXN0ZW0xIjAgBgkq
    hkiG9w0BCQEWE2luZm9AYWNwLmFjcC1zeXN0ZW0wHhcNMjExMjEzMDA0MDExWhcN
    MjIxMjEzMDA0MDExWjCBiDELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAldBMRAwDgYD
    VQQHDAdTZWF0dGxlMRQwEgYDVQQKDAtDbG91ZGVudGl0eTELMAkGA1UECwwCU0Ux
    EzARBgNVBAMMCmFjcC1zeXN0ZW0xIjAgBgkqhkiG9w0BCQEWE2luZm9AYWNwLmFj
    cC1zeXN0ZW0wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDBJdr9bgGx
    fE3nHl/oCYYSMpowkGmbSDUijHNA8p47q+7VgC0AXS5iScySiUptfEn8UdilvhKR
    Fdtfz7epp4zsZSLYQpAafmTrBP4eJLE240dm1k0egp6/cho6S7DdrF8loJoJs+84
    GhDJonX5ktIQAXEOc25CBwukxYUk09x+aiqsFD25Ohxpqc/6Yari3ibfhbZ6aDIR
    EDMze34oM95c86DJGg9nuKfdkC44MbcG0kGByF3+JUwLQ2cWU2+8BHN/mW4VTgRS
    yilX2iXwumvtE00GpMr2xoUsLHC3Vetp7en+3hUE/DulcdTQFyXDqipDZIwSfI+O
    2llr+SlsexzxAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAK3p6DRNsJTZhuA5zBey
    QPKlAtYWGa2Y3JdTNg5qR6tbrATD42A05zFmAqCppSKCcOEdg0SrRONXC709IW36
    dE/W1roNrcdQVV2xXdSFt4+7I5pfjdl3hq0xC67fau8QMfAfxHxZe3BnEQinT+bn
    joYu3RdMigwq/36cuuVIOQsKm1ukYH66+sWCRs48yKc3a0o56uLM783Cn3l2KtdQ
    a1gohl732YrZOA45IPu19EuckfiYSfXF6X5Dc6POYRPF+VJVXF3RaZfOEN6so2WW
    eGimUwKTQVKERIMHGwb/WuGlQ1AZEb2GqoRkdIoVqZgNuk9bouikvU2U9yQOf+si
    mqE=
    -----END CERTIFICATE-----
config:
  ## The data should match acp configuration options
  ## https://docs.operations.cloudentity.com/reference/acp-configuration/
  ##
  data:
    client:
        insecure_skip_verify: false

data:
  gateways:
    - tenant_id: default
      authorization_server_id: default
      id: local-istio-authorizer
      client_id: local-istio-authorizer-client
      client_secret: cf53caac-fb55-40a7-8c63-620ce11102e2
      name: Local Istio Authorizer
      description: Local imported Istio Authorizer
      type: istio
      create_and_bind_services_automatically: true
  clients:
    - tenant_id: default
      authorization_server_id: system
      client_id: local-istio-authorizer-client
      client_secret: cf53caac-fb55-40a7-8c63-620ce11102e2
      token_endpoint_auth_method: client_secret_basic
      system: false
      trusted: false
      client_name: Local Istio Authorizer client
      application_type: web
      grant_types:
        - client_credentials
      response_types:
        - code
      scopes:
        - introspect_tokens
        - push_gateway_requests
        - read_gateway_configuration
        - write_gateway_configuration

```

**Comment by ppodbielski-cloudentity** [comment]
@lradosz I added podSecurityContext

**Review by mbilski — APPROVED** [review]

**Review by lgonczarik — APPROVED** [review]

**Pull request merged**
